[proxmox]
psyche ansible_host=10.0.0.100 ansible_user=root
# If you run this playbook directly on the Proxmox node instead of over SSH,
# replace the line above with:
# pve01 ansible_connection=local
